/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entidade.Mercadorias;
import entidade.Status;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Convidado1
 */
public class Comida extends javax.swing.JDialog {

    Status st;
    Mercadorias m;

    public Comida(java.awt.Frame parentFrame, boolean modal, Status st, Mercadorias m) {
        super(parentFrame, modal);
        this.st = st;
        this.m = m;
        initComponents();
        btnPao.setEnabled(false);
        btnBeterraba.setEnabled(false);
        btnChocolate.setEnabled(false);
        btnBoloMorango.setEnabled(false);
        btnPao.setText("Pão: " + m.getPao());
        btnBeterraba.setText("Beterraba: " + m.getBeterraba());
        btnBoloMorango.setText("Bolo de Morango: " + m.getBoloMorango());
        btnChocolate.setText("Chocolate: " + m.getChocolate());
        st.t = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (m.getPao() > 0) {
                    btnPao.setEnabled(true);
                } else{
                     btnPao.setEnabled(false);
                }
                if (m.getBeterraba() > 0) {
                    btnBeterraba.setEnabled(true);
                } else{
                    btnBeterraba.setEnabled(false);
                }
                if (m.getChocolate() > 0) {
                    btnChocolate.setEnabled(true);
                } else{
                    btnChocolate.setEnabled(false);
                }
                if (m.getBoloMorango() > 0) {
                    btnBoloMorango.setEnabled(true);
                } else{
                    btnBoloMorango.setEnabled(false);
                }
            }
        });
        st.t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRacao = new javax.swing.JButton();
        btnPao = new javax.swing.JButton();
        btnChocolate = new javax.swing.JButton();
        btnBeterraba = new javax.swing.JButton();
        btnBoloMorango = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Armário de comida");

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Comida");

        btnRacao.setText("Ração");
        btnRacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRacaoActionPerformed(evt);
            }
        });

        btnPao.setText("Pão");
        btnPao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaoActionPerformed(evt);
            }
        });

        btnChocolate.setText("Chocolate");
        btnChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChocolateActionPerformed(evt);
            }
        });

        btnBeterraba.setText("Beterraba");
        btnBeterraba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeterrabaActionPerformed(evt);
            }
        });

        btnBoloMorango.setText("Bolo de Morango");
        btnBoloMorango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoloMorangoActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPao, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBoloMorango, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnFechar)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBeterraba, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(137, 137, 137))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnRacao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPao)
                    .addComponent(btnBoloMorango))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChocolate)
                    .addComponent(btnBeterraba))
                .addGap(18, 18, 18)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRacaoActionPerformed
        st.aumentarComida(10);
        btnRacao.setEnabled(false);
        st.t = new Timer(60000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnRacao.setEnabled(true);
                st.t.stop();
            }
        });
        st.t.start();
    }//GEN-LAST:event_btnRacaoActionPerformed

    private void btnPaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaoActionPerformed
        if (m.getPao() > 0) {
            st.aumentarComida(18);
            m.diminuirPao(1);
            btnPao.setText("Pão: " + m.getPao());
        } else {
            btnPao.setEnabled(false);
        }
    }//GEN-LAST:event_btnPaoActionPerformed

    private void btnChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChocolateActionPerformed
        if (m.getChocolate() > 0) {
            st.aumentarComida(25);
            m.diminuirChocolate(1);
            btnChocolate.setText("Chocolate: " + m.getChocolate());
        } else {
            btnChocolate.setEnabled(false);
        }
    }//GEN-LAST:event_btnChocolateActionPerformed

    private void btnBeterrabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeterrabaActionPerformed
        if (m.getBeterraba() > 0) {
            st.aumentarComida(30);
            m.diminuirBeterraba(1);
            btnBeterraba.setText("Beterraba: " + m.getBeterraba());
        } else {
            btnBeterraba.setEnabled(false);
        }
    }//GEN-LAST:event_btnBeterrabaActionPerformed

    private void btnBoloMorangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoloMorangoActionPerformed
        if (m.getBoloMorango() > 0) {
            st.aumentarComida(70);
            m.diminuirBoloMorango(1);
            btnBoloMorango.setText("Bolo de Morango: " + m.getBoloMorango());
        } else {
            btnBoloMorango.setEnabled(false);
        }
    }//GEN-LAST:event_btnBoloMorangoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        Comida.this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Comida dialog = new Comida(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeterraba;
    private javax.swing.JButton btnBoloMorango;
    private javax.swing.JButton btnChocolate;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPao;
    private javax.swing.JButton btnRacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
