/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entidade.Mercadorias;
import entidade.Status;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Convidado1
 */
public class Quarto extends javax.swing.JDialog {

    Status st;
    Mercadorias m;

    public Quarto(java.awt.Frame parent, boolean modal, Status st, Mercadorias m) {
        super(parent, modal);
        this.st = st;
        this.m=m;
        initComponents();
        btnCamaBox.setEnabled(false);
        btnCamaMadeira.setEnabled(false);
        btnSacoDormir.setEnabled(false);
        
                if (m.getContSacoDormir() == 1) {
                    btnSacoDormir.setEnabled(true);
                    btnDormirChao.setEnabled(false);
                } else {
                    btnSacoDormir.setEnabled(false);
                }
                if (m.getContCamaMadeira()== 1) {
                    btnCamaMadeira.setEnabled(true);
                    btnDormirChao.setEnabled(false);
                } else {
                    btnCamaMadeira.setEnabled(false);
                }
                if (m.getContCamaBox()== 1) {
                    btnCamaBox.setEnabled(true);
                    btnDormirChao.setEnabled(false);
                } else {
                    btnCamaBox.setEnabled(false);
                }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDormirChao = new javax.swing.JButton();
        btnSacoDormir = new javax.swing.JButton();
        btnCamaMadeira = new javax.swing.JButton();
        btnCamaBox = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Quarto");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Quarto");

        btnDormirChao.setText("Dormir no chão");
        btnDormirChao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDormirChaoActionPerformed(evt);
            }
        });

        btnSacoDormir.setText("Saco de dormir");
        btnSacoDormir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacoDormirActionPerformed(evt);
            }
        });

        btnCamaMadeira.setText("Cama de madeira");
        btnCamaMadeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamaMadeiraActionPerformed(evt);
            }
        });

        btnCamaBox.setText("Cama box");
        btnCamaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamaBoxActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDormirChao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSacoDormir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCamaMadeira)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCamaBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDormirChao)
                    .addComponent(btnSacoDormir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCamaMadeira)
                    .addComponent(btnCamaBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDormirChaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDormirChaoActionPerformed
        btnDormirChao.setEnabled(false);
        st.aumentarDisposicao(10);
        if(m.getSacoDormir()==0 || m.getCamaBox()==0 || m.getCamaMadeira()==0){
            st.t = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btnDormirChao.setEnabled(true);
                    st.t.stop();
                }
            });
            st.t.start();
        }
    }//GEN-LAST:event_btnDormirChaoActionPerformed

    private void btnSacoDormirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacoDormirActionPerformed
        btnSacoDormir.setEnabled(false);
        st.aumentarDisposicao(18);
        btnDormirChao.setEnabled(false);
        st.t = new Timer(90000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnSacoDormir.setEnabled(true);
                st.t.stop();
            }
        });
        st.t.start();
    }//GEN-LAST:event_btnSacoDormirActionPerformed

    private void btnCamaMadeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamaMadeiraActionPerformed
        btnCamaMadeira.setEnabled(false);
        st.aumentarDisposicao(30);
        st.t = new Timer(90000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnCamaMadeira.setEnabled(true);
                st.t.stop();
            }
        });
        st.t.start();
    }//GEN-LAST:event_btnCamaMadeiraActionPerformed

    private void btnCamaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamaBoxActionPerformed
        btnCamaBox.setEnabled(false);
        st.aumentarDisposicao(50);
        st.t = new Timer(90000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnCamaBox.setEnabled(true);
                st.t.stop();
            }
        });
        st.t.start();
    }//GEN-LAST:event_btnCamaBoxActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        Quarto.this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Quarto dialog = new Quarto(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCamaBox;
    private javax.swing.JButton btnCamaMadeira;
    private javax.swing.JButton btnDormirChao;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSacoDormir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
